# Generated by Django 5.2.8 on 2025-11-27 11:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("player", "Player"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                            ("super_admin", "Super Admin"),
                        ],
                        default="player",
                        help_text="User role determines access level",
                        max_length=20,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        help_text="Account status",
                        max_length=20,
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, help_text="Whether email has been verified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jersey_number",
                    models.IntegerField(
                        blank=True, help_text="Player jersey number", null=True
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PG", "Point Guard"),
                            ("SG", "Shooting Guard"),
                            ("SF", "Small Forward"),
                            ("PF", "Power Forward"),
                            ("C", "Center"),
                        ],
                        help_text="Primary playing position",
                        max_length=50,
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        help_text="Player height (e.g., 6'2\")",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="Player weight (e.g., 180 lbs)",
                        max_length=20,
                    ),
                ),
                (
                    "hometown",
                    models.CharField(
                        blank=True, help_text="Player hometown", max_length=100
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Player biography")),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Player profile photo",
                        null=True,
                        upload_to="players/photos/",
                    ),
                ),
                (
                    "years_active",
                    models.CharField(
                        blank=True,
                        help_text="Years active (e.g., 2020-Present)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        help_text="Player status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Related user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Player",
                "verbose_name_plural": "Players",
                "db_table": "players",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="users_status_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["status"], name="players_status_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["jersey_number"], name="players_jersey_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["position"], name="players_position_idx"),
        ),
    ]
