# Generated by Django 5.2.4 on 2025-12-21 09:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon name (e.g., award, users, target, heart)",
                        max_length=50,
                    ),
                ),
                (
                    "color_start",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Gradient start color",
                        max_length=50,
                    ),
                ),
                (
                    "color_end",
                    models.CharField(
                        default="#60a5fa", help_text="Gradient end color", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pages_core_values",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AlterModelOptions(
            name="historytimeline",
            options={"ordering": ["order", "-year"]},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="sponsor",
            options={"ordering": ["order", "name"]},
        ),
        migrations.RemoveField(
            model_name="faq",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="historytimeline",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="page",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="page",
            name="menu_order",
        ),
        migrations.RemoveField(
            model_name="page",
            name="show_in_menu",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_short",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="city",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="country",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="logo_dark",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="mission",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="tiktok_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vision",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="page",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="pages/hero/"),
        ),
        migrations.AddField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, help_text="Main about content"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title",
            field=models.CharField(blank=True, default="About TBWS", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_title",
            field=models.CharField(blank=True, default="Our Mission", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title",
            field=models.CharField(blank=True, default="Our Vision", max_length=200),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="started_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="joined_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historytimeline",
            name="is_milestone",
            field=models.BooleanField(
                default=False, help_text="Mark as a major milestone"
            ),
        ),
        migrations.AlterField(
            model_name="historytimeline",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="historytimeline",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="page",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="pages/featured/"),
        ),
        migrations.AlterField(
            model_name="page",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="TBWS", max_length=100),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("treasurer", "Treasurer"),
                    ("committee", "Committee Member"),
                    ("coach", "Coach"),
                    ("staff", "Staff"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name="sponsor",
            table="pages_sponsors",
        ),
        migrations.AlterModelTable(
            name="teammember",
            table="pages_team_members",
        ),
    ]
