# Generated by Django 5.2.4 on 2025-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_corevalue_alter_faq_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Main hero section image",
                null=True,
                upload_to="site/hero/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True, help_text="Browser favicon", null=True, upload_to="site/"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="Main site logo", null=True, upload_to="site/"
            ),
        ),
    ]
