# Generated by Django 5.2.4 on 2025-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_sitesettings_hero_image_alter_sitesettings_favicon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_image",
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
    ]
