# Generated by Django 5.2.4 on 2025-12-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_sitesettings_hero_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Main hero section image",
                null=True,
                upload_to="site/hero/",
            ),
        ),
        migrations.AlterField(
            model_name="corevalue",
            name="color_end",
            field=models.CharField(
                default="#60a5fa", help_text="Gradient end color (hex)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="corevalue",
            name="color_start",
            field=models.CharField(
                default="#3b82f6", help_text="Gradient start color (hex)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="corevalue",
            name="icon",
            field=models.CharField(
                help_text="Icon name (award, users, target, heart, sparkles, trending)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True, help_text="Browser favicon", null=True, upload_to="site/"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="Main site logo", null=True, upload_to="site/"
            ),
        ),
    ]
