# Generated by Django 5.2.4 on 2025-12-21 21:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_sitesettings_hero_image_alter_corevalue_color_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="TBWS Draft Process", max_length=200),
                ),
                (
                    "overview",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="General overview of the draft"
                    ),
                ),
                (
                    "eligibility_title",
                    models.CharField(
                        blank=True, default="Eligibility Requirements", max_length=200
                    ),
                ),
                (
                    "eligibility_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "process_title",
                    models.CharField(
                        blank=True, default="How It Works", max_length=200
                    ),
                ),
                (
                    "process_content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Step-by-step draft process"
                    ),
                ),
                (
                    "timeline_title",
                    models.CharField(
                        blank=True, default="Draft Timeline", max_length=200
                    ),
                ),
                (
                    "timeline_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "rules_title",
                    models.CharField(blank=True, default="Draft Rules", max_length=200),
                ),
                (
                    "rules_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "faq_title",
                    models.CharField(blank=True, default="Draft FAQ", max_length=200),
                ),
                (
                    "faq_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("draft_date", models.DateTimeField(blank=True, null=True)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="draft/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Draft Information",
                "verbose_name_plural": "Draft Information",
                "db_table": "pages_draft_info",
            },
        ),
        migrations.CreateModel(
            name="LeagueRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("game_rules", "Game Rules"),
                            ("player_rules", "Player Rules"),
                            ("team_rules", "Team Rules"),
                            ("conduct", "Code of Conduct"),
                            ("eligibility", "Eligibility"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "League Rule",
                "verbose_name_plural": "League Rules",
                "db_table": "pages_league_rules",
                "ordering": ["category", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team_name", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="managers/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "years_experience",
                    models.IntegerField(
                        blank=True, help_text="Years as manager", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pages_managers",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ManagerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Team Manager Information", max_length=200
                    ),
                ),
                (
                    "overview",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="What is a team manager?"
                    ),
                ),
                (
                    "responsibilities_title",
                    models.CharField(
                        blank=True, default="Manager Responsibilities", max_length=200
                    ),
                ),
                (
                    "responsibilities_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "requirements_title",
                    models.CharField(
                        blank=True, default="Requirements", max_length=200
                    ),
                ),
                (
                    "requirements_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "benefits_title",
                    models.CharField(blank=True, default="Benefits", max_length=200),
                ),
                (
                    "benefits_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "how_to_become_title",
                    models.CharField(
                        blank=True, default="How to Become a Manager", max_length=200
                    ),
                ),
                (
                    "how_to_become_content",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Manager Information",
                "verbose_name_plural": "Manager Information",
                "db_table": "pages_manager_info",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "court_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Indoor, Outdoor, Hardwood",
                        max_length=100,
                    ),
                ),
                (
                    "court_dimensions",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Full court, Half court",
                        max_length=100,
                    ),
                ),
                (
                    "surface_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Hardwood, Concrete, Asphalt",
                        max_length=100,
                    ),
                ),
                (
                    "facilities",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Locker rooms, parking, seating, etc."
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, help_text="Spectator capacity", null=True
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="venues/"),
                ),
                (
                    "gallery_images",
                    models.TextField(
                        blank=True, help_text="Comma-separated image URLs"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "map_embed_code",
                    models.TextField(
                        blank=True, help_text="Google Maps embed iframe code"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Primary home court"),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pages_venues",
                "ordering": ["-is_primary", "order", "name"],
            },
        ),
    ]
