# Generated by Django 5.2.4 on 2025-12-24 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryalbum",
            options={
                "ordering": ["-is_featured", "order", "-created_at"],
                "verbose_name": "Gallery Album",
                "verbose_name_plural": "Gallery Albums",
            },
        ),
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "ordering": ["-is_featured", "order", "-uploaded_at"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
