# Generated by Django 5.2.4 on 2025-12-02 10:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Team name (e.g., "Tusker Warriors")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text='Short name or abbreviation (e.g., "Warriors")',
                        max_length=50,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name", max_length=100, unique=True
                    ),
                ),
                (
                    "founded_date",
                    models.DateField(
                        blank=True, help_text="Date team was founded", null=True
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("men", "Men"),
                            ("women", "Women"),
                            ("youth", "Youth"),
                            ("mixed", "Mixed"),
                        ],
                        default="men",
                        help_text="Team division",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Team description or history"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Team logo",
                        null=True,
                        upload_to="teams/logos/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1e3c72",
                        help_text="Primary team color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#2a5298",
                        help_text="Secondary team color (hex code)",
                        max_length=7,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Team contact email", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Team contact phone", max_length=20
                    ),
                ),
                (
                    "home_venue",
                    models.CharField(
                        blank=True, help_text="Home court/venue", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("disbanded", "Disbanded"),
                        ],
                        default="active",
                        help_text="Team status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assistant_coaches",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Assistant coaches",
                        related_name="assistant_coached_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "head_coach",
                    models.ForeignKey(
                        blank=True,
                        help_text="Head coach of the team",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("player", "Player"),
                            ("captain", "Captain"),
                            ("vice_captain", "Vice Captain"),
                        ],
                        default="player",
                        help_text="Player role on team",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("injured", "Injured"),
                            ("suspended", "Suspended"),
                            ("left", "Left Team"),
                        ],
                        default="active",
                        help_text="Membership status",
                        max_length=20,
                    ),
                ),
                (
                    "jersey_number",
                    models.PositiveIntegerField(
                        help_text="Jersey number (0-99)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "joined_date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Date joined team"
                    ),
                ),
                (
                    "left_date",
                    models.DateField(blank=True, help_text="Date left team", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Player",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="users.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "team_members",
                "ordering": ["jersey_number"],
            },
        ),
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        help_text='Season (e.g., "2024", "2024-25")', max_length=20
                    ),
                ),
                (
                    "games_played",
                    models.PositiveIntegerField(
                        default=0, help_text="Total games played"
                    ),
                ),
                (
                    "wins",
                    models.PositiveIntegerField(default=0, help_text="Total wins"),
                ),
                (
                    "losses",
                    models.PositiveIntegerField(default=0, help_text="Total losses"),
                ),
                (
                    "points_scored",
                    models.PositiveIntegerField(
                        default=0, help_text="Total points scored"
                    ),
                ),
                (
                    "points_allowed",
                    models.PositiveIntegerField(
                        default=0, help_text="Total points allowed"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Current win/loss streak (positive for wins, negative for losses)",
                    ),
                ),
                (
                    "longest_win_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Longest winning streak"
                    ),
                ),
                (
                    "longest_loss_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Longest losing streak"
                    ),
                ),
                (
                    "league_rank",
                    models.PositiveIntegerField(
                        blank=True, help_text="Current league ranking", null=True
                    ),
                ),
                (
                    "division_rank",
                    models.PositiveIntegerField(
                        blank=True, help_text="Current division ranking", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Statistics",
                "verbose_name_plural": "Team Statistics",
                "db_table": "team_stats",
                "ordering": ["-season", "-wins"],
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["slug"], name="team_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["status", "division"], name="team_status_div_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["-created_at"], name="team_created_idx"),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "status"], name="member_team_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["player", "status"], name="member_player_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "jersey_number", "status"), ("team", "player")},
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(
                fields=["season", "-wins"], name="stats_season_wins_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamstats",
            index=models.Index(fields=["team", "season"], name="stats_team_season_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamstats",
            unique_together={("team", "season")},
        ),
    ]
